### ISSUE TITLE
setting `selenium_exclude_debug = url` removes screenshot

### ISSUE THREAD

**Issue by birdsarah** [davehunt/pytest-selenium#52]
I'm not sure what this option is meant to do, but I was surprised when it removed the screenshot from my test failure report. Can you clarify each of the options to `selenium_exclude_debug`

**Comment by davehunt** [comment]
This sounds like a bug, the expected behaviour is documented [here](https://pytest-selenium.readthedocs.org/en/latest/user_guide.html#excluding-debug), so setting `selenium_exclude_debug` to `url` should only exclude the URL from the HTML report. The relevant code is [here](https://github.com/davehunt/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L105-L113).

**Comment by birdsarah** [comment]
Hi, yes, the documentation you point to is not sufficient, it just says "The debug types are: html, logs, screenshot and url." I don't know what these actually are or are collecting. Screenshot's fairly self-explanatory but the rest aren't.

This may be two seperate issues a bug and a documentation problem.

**Comment by davehunt** [comment]
@birdsarah I've written test for exclude and capture debug in #54 and they're all passing as expected for me. Can you confirm that by setting `selenium_exclude_debug` to `url` you are not getting a screenshot in your HTML report? Also, what version of Python are you using?

**Comment by davehunt** [comment]
The new tests failed in Python 3.x, which I suspect is the issue you're seeing. I intend to work on Python 3 compatibility for the next release.

**Comment by davehunt** [comment]
The bug should be fixed by #55 and I've improved the documentation in https://github.com/davehunt/pytest-selenium/commit/a5eaa40d76f3d625a948b4d1efa328f1e1229bfd.
